Draft: Add support for text2ascii_char
OpenDreamProject/OpenDream pull request #1096
Opened 2023-03-16 14:59 UTC by Inorien

Resolves #1028 

References example from [byond unicode documentation](https://www.byond.com/docs/ref/#/{notes}/Unicode)

Tests:
```
world << text2ascii("abcdéfg",6)
world << ascii2text(text2ascii("abcdéfg",6))
world << text2ascii_char("abcdéfg",6)
world << ascii2text(text2ascii_char("abcdéfg",6))
```

`text2ascii` is a bytewise index while `text2ascii_char` is wise to character widths.

byond output:
```
65533
 
102
f
```

byond realises when a byte is being badly read and sets the return to `0xfffd` (65533). This happened because `text2ascii("abcdéfg", 6)` hits byte 6, which is the second half of the `é` character.

opendream output:
```
102
f
102
f
```

opendream implementation of `text2ascii` uses inbuilt C# string operations which is all in UTF-16, this is known to break compatibility

2023-03-16 17:08 UTC, amylizzle commented
It'd be good if you added a test file for this, just to demonstrate that it works and prevent future reversion.

2023-03-17 00:57 UTC, Inorien commented
> It'd be good if you added a test file for this, just to demonstrate that it works and prevent future reversion.

agreed, it was getting late last night and i wanted to get the commit down before figuring out unit tests

will open future PRs in draft if not ready

2023-03-17 12:31 UTC, Inorien commented
unit test throws following for some reason:

```
 A DM runtime exception was thrown: "OpenDreamRuntime.DMCrashRuntime
   at OpenDreamRuntime.Procs.Native.DreamProcNativeRoot.NativeProc_CRASH(DreamObject instance, DreamObject usr, DreamProcArguments arguments) in C:\Users\NickF\code\OpenDream\OpenDreamRuntime\Procs\Native\DreamProcNativeRoot.cs:line 311
   at OpenDreamRuntime.Procs.NativeProc.State.Resume() in C:\Users\NickF\code\OpenDream\OpenDreamRuntime\Procs\NativeProc.cs:line 53
   at OpenDreamRuntime.DreamThread.Resume() in C:\Users\NickF\code\OpenDream\OpenDreamRuntime\DreamThread.cs:line 231"
  Expected: True
  But was:  False
```
still investigating

2023-03-17 12:46 UTC, amylizzle commented
That's your `ASSERT()` failing.

2023-03-17 14:24 UTC, Inorien commented
all part of the learning process!

2023-03-18 05:31 UTC, wixoaGit commented
> all part of the learning process!

It normally would have shown the `ASSERT()` error message alongside it, but that was recently broken. It's fixed in #1104.

2023-03-18 21:26 UTC, wixoaGit requested changes

2023-03-18 21:26 UTC, wixoaGit commented on Content.Tests/DMProject/Tests/Builtins/text2ascii_char.dm
> +	world << text2ascii_char("abcdéfg",6)
This line doesn't do anything (there are no connected clients) and is unnecessary
```suggestion
```

2023-03-19 00:33 UTC, wixoaGit approved these changes

2023-03-19 00:39 UTC, merged