Increase the max stack depth to 400
OpenDreamProject/OpenDream pull request #1103
Opened 2023-03-18 01:15 UTC by ike709

![image](https://user-images.githubusercontent.com/5714543/226075447-617ea228-7d9d-496b-8a57-ac46577d2c1e.png)

2023-03-19 20:00 UTC, out-of-phaze commented
More accurately, it's 400 for the `loop_checks = TRUE` warning. BYOND's actual hard stack limit is like... 3606-3609, according to Kapu.

2023-03-28 02:18 UTC, wixoaGit commented
> More accurately, it's 400 for the `loop_checks = TRUE` warning. BYOND's actual hard stack limit is like... 3606-3609, according to Kapu.

400 is likely a large enough cap, if we run into legitimate issues with it we can raise it again.

2023-03-28 02:20 UTC, wixoaGit requested changes

2023-03-28 02:38 UTC, wixoaGit approved these changes

2023-03-28 02:42 UTC, merged