Add some math procs to IsValidRighthandSide
OpenDreamProject/OpenDream pull request #1202
Opened 2023-05-01 20:08 UTC by pali6

Added only those that BYOND considers const-evaluable (no `round` for example).

2023-05-01 23:11 UTC, pali6 commented
Huh, locally tests were passing. Will check what's wrong tomorrow. Also I should remove the native proc implementations now.

2023-05-02 09:21 UTC, pali6 commented
The unit test uses approximate equality because of the fact that .NET's trigonometry functions can and do behave differently on different platforms. See the remark [here](https://learn.microsoft.com/en-us/dotnet/api/system.mathf.tan?view=net-5.0). There is apparently a 1.1920929E-07 difference between Windows and Linux (or at least between my computer and the github actions server). Maybe at some point we will have to use something else than MathF and Math to avoid this issue.

2023-10-02 19:17 UTC, wixoaGit requested changes

2023-10-02 19:17 UTC, wixoaGit commented on OpenDreamRuntime/Procs/DMOpcodeHandlers.cs
> +
`UnsafeGetValueAsFloat()`
```suggestion
            state.Push(new DreamValue(MathF.Log(value.UnsafeGetValueAsFloat(), baseValue.UnsafeGetValueAsFloat())));
```

2023-10-02 19:17 UTC, wixoaGit commented on OpenDreamRuntime/Procs/DMOpcodeHandlers.cs
> +
`UnsafeGetValueAsFloat()`
```suggestion
            state.Push(new DreamValue(MathF.Abs(value.UnsafeGetValueAsFloat())));
```

2023-10-02 19:17 UTC, wixoaGit commented on OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
> +    static class DreamProcNativeRoot {
Don't remove `internal`
```suggestion
    internal static class DreamProcNativeRoot {
```

2023-10-02 19:17 UTC, wixoaGit commented on Content.Tests/DMProject/Tests/Expression/const_eval.dm
> +#define EPSILON 1e-6
Require less precision now that the arc procs are single-precision
```suggestion
#define EPSILON 4e-6
```

2023-10-04 02:38 UTC, wixoaGit approved these changes

2023-10-04 02:38 UTC, merged