Seal the compiler
OpenDreamProject/OpenDream pull request #1219
Opened 2023-05-06 05:17 UTC by ike709

Imports Robust's analyzers, mainly the one to mark classes as `sealed` whenever possible as a really minor (but free) optimization.

2023-05-10 18:41 UTC, wixoaGit requested changes

2023-05-10 18:41 UTC, wixoaGit commented on DMCompiler/Compiler/DM/DMASTHelper.cs
> +using Robust.Shared.Analyzers;
This should be using the VirtualAttribute from `DMCompiler` not `Robust.Shared.Analyzers`

2023-05-13 21:05 UTC, ike709 commented
I nuked the analyzer since it relies on the Robust namespace. This just seals up everything that the analyzer warned about.

2023-05-15 16:03 UTC, wixoaGit requested changes

2023-05-15 16:03 UTC, wixoaGit commented on DMCompiler/Compiler/DM/DMParser.cs
> +using Robust.Shared.Analyzers;
```suggestion
```

2023-05-15 16:03 UTC, wixoaGit commented on DMCompiler/DMCompiler.csproj
> +
```suggestion
```

2023-05-15 16:12 UTC, merged