Displacement filter
OpenDreamProject/OpenDream pull request #1243
Opened 2023-05-20 11:25 UTC by amylizzle

![image](https://github.com/OpenDreamProject/OpenDream/assets/3855802/2b14ca1b-c715-43d5-ac77-e767f31644a9)

2023-05-22 00:16 UTC, wixoaGit requested changes
The filter doesn't have the same affect as it does in BYOND
![image](https://github.com/OpenDreamProject/OpenDream/assets/30789242/76575a49-4293-4dd4-8b72-8e39c3121b55)
BYOND on the left

2023-05-22 00:16 UTC, wixoaGit commented on TestGame/icons/displace.dmi
This needs added to the [solution file](https://github.com/OpenDreamProject/OpenDream/blob/master/OpenDream.sln#L15) so it's visible within the IDE

2023-05-22 09:53 UTC, amylizzle commented
Close, but no cigar 
![image](https://github.com/OpenDreamProject/OpenDream/assets/3855802/eb7c16e9-79a8-41e7-9713-24104d03a1a1)

2023-05-22 12:11 UTC, amylizzle commented
Done 
![image](https://github.com/OpenDreamProject/OpenDream/assets/3855802/cd4f8a30-4cdd-43f5-8fef-bd6e867da79c)

Minor differences are due to sampling algorithm and different `world.view` sizes I'm pretty sure. Sampling algo isn't exposed to content though, so we'll have to fix that in the upstream RT.

2023-05-23 04:20 UTC, wixoaGit approved these changes

2023-05-23 04:20 UTC, merged