Make \ref[] format the same as byond
OpenDreamProject/OpenDream pull request #1319
Opened 2023-06-21 14:31 UTC by amylizzle

type IDs are different, but otherwise make \ref return a string formatted like `0x1000000`

2023-06-23 18:59 UTC, wixoaGit commented
Could you also wrap the ref in `[]` and give lists the ID `0xf`? SS13's view variables uses this to determine if a list is a special list.

2023-06-24 03:58 UTC, wixoaGit requested changes

2023-06-24 03:58 UTC, wixoaGit commented on OpenDreamRuntime/DreamManager.cs
> +                                refType = RefType.DreamObject;
Ref ID 0xF should be reserved for DreamList but not any of its descendants.
```suggestion
                        default: {
                            refType = RefType.DreamObjectDatum;
                            if(refObject.IsSubtypeOf(_objectTree.Obj))
                                refType = RefType.DreamObject;
                            else if (refObject.GetType() == typeof(DreamList))
                                refType = RefType.DreamObjectList;
```

2023-06-24 03:58 UTC, wixoaGit commented on OpenDreamRuntime/DreamManager.cs
> +            return $"[0x{((int) refType+idx):X}]";
BYOND gives these in lowercase
```suggestion
            return $"[0x{((int) refType+idx):x}]";
```

2023-06-24 03:58 UTC, wixoaGit commented on OpenDreamRuntime/IDreamManager.cs
> +        DreamResource = 0xFF000000, //doesn't exist in byond
This would be the equivalent to a file (0x27 in BYOND)

2023-06-24 10:40 UTC, amylizzle commented on OpenDreamRuntime/IDreamManager.cs
> +        DreamResource = 0xFF000000, //doesn't exist in byond
```suggestion
        DreamResource = 0x27000000, //Equivalent to file
```

2023-06-24 10:40 UTC, amylizzle commented on Content.Tests/DMProject/Tests/Text/ref.dm
> +	ASSERT(lowertext(copytext("\ref[test]",4,5)) == "f")
```suggestion
	ASSERT(copytext("\ref[test]",4,5) == "f")
```

2023-06-24 23:25 UTC, wixoaGit requested changes

2023-06-24 23:25 UTC, wixoaGit commented on Content.Tests/DMProject/Tests/Text/ref.dm
> +#define ASSERT(expr) ((expr) ? null : CRASH("Assertion Failed: " + #expr))
No need to re-define `ASSERT()`
```suggestion
```

2023-06-24 23:25 UTC, wixoaGit approved these changes

2023-06-24 23:30 UTC, merged