Resource fixes, ACZ resources
OpenDreamProject/OpenDream pull request #1358
Opened 2023-07-04 23:13 UTC by PJB3005

:tada:

Means resource downloads won't suck for the next playtest.

2023-07-05 05:42 UTC, wixoaGit commented
The RT submodule needs to be updated

2023-07-05 06:11 UTC, wixoaGit requested changes

2023-07-05 22:14 UTC, PJB3005 commented on OpenDreamClient/Resources/DreamResourceManager.cs
>                  });
Oops, debugging code.

2023-07-06 01:42 UTC, wixoaGit approved these changes

2023-07-06 01:42 UTC, merged