Optimize `Increment`/`Decrement`
OpenDreamProject/OpenDream pull request #1372
Opened 2023-07-13 23:10 UTC by ike709

Credit to moony who is just too lazy to PR it.

The typechecking was redundant.

2023-07-13 23:22 UTC, moonheart08 commented
thief

2023-07-14 22:09 UTC, wixoaGit requested changes

2023-07-14 22:09 UTC, wixoaGit commented on OpenDreamRuntime/Procs/DMOpcodeHandlers.cs
> +            state.AssignReference(reference, new(value.UnsafeGetValueAsInteger() + 1));
Keep the comment, it's useful context
```suggestion
            //If it's not a number, it turns into 1
            state.AssignReference(reference, new(value.UnsafeGetValueAsInteger() + 1));
```

2023-07-14 22:09 UTC, wixoaGit commented on OpenDreamRuntime/Procs/DMOpcodeHandlers.cs
> +            state.AssignReference(reference, new(value.UnsafeGetValueAsInteger() - 1));
```suggestion
            //If it's not a number, it turns into -1
            state.AssignReference(reference, new(value.UnsafeGetValueAsInteger() - 1));
```

2023-07-14 22:16 UTC, wixoaGit approved these changes

2023-07-14 22:22 UTC, merged