Fully implement splittext and add test
OpenDreamProject/OpenDream pull request #1560
Opened 2023-12-22 16:52 UTC by amylizzle

Slight BYOND parity break due to what looks like a bug https://www.byond.com/forum/post/2904976

2024-01-06 11:26 UTC, amylizzle commented on Content.Tests/DMProject/Tests/Text/Splittext.dm
> +		ASSERT(A[i] == B[i])
Completely forgot that existed

2024-01-07 01:42 UTC, wixoaGit requested changes

2024-01-07 01:42 UTC, wixoaGit commented on Content.Tests/DMProject/Tests/Text/Splittext.dm
> +	ASSERT(A ~= B)
This entire helper proc can be removed and replaced with `ASSERT(testX ~= testX_expected)`

2024-01-07 01:42 UTC, wixoaGit commented on OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
> +                includeDelimiters = include_delimiters_int != 0; //idk why BYOND doesn't just use truthiness, but it doesn't, so...
Rename to `includeDelimitersInt`
```suggestion
            if(bundle.GetArgument(4, "include_delimiters").TryGetValueAsInteger(out var includeDelimitersInt))
                includeDelimiters = includeDelimitersInt != 0; //idk why BYOND doesn't just use truthiness, but it doesn't, so...
```

2024-01-07 17:27 UTC, wixoaGit requested changes

2024-01-07 17:27 UTC, wixoaGit commented on Content.Tests/DMProject/Tests/Text/Splittext.dm
> +	test1 ~= test1_expected
These need to `ASSERT()`

2024-01-07 17:32 UTC, amylizzle commented on Content.Tests/DMProject/Tests/Text/Splittext.dm
> +	test1 ~= test1_expected
I'm an idiot

2024-01-07 17:35 UTC, wixoaGit approved these changes

2024-01-07 19:16 UTC, merged