Tweak `Nameof` slightly, add `GetNameof()` support to more expressions
OpenDreamProject/OpenDream pull request #1618
Opened 2024-01-10 14:47 UTC by distributivgesetz

Throwing is bad. Unwinding ain't healthy for tracking errors. I refactored `GetNameof()` to return an optional string, which gets checked in the actual `Nameof` expression. There we can emit the error. 

The arguments for `GetNameof` felt unnecessary since `dmObject` was unused, `proc` was used only once in `Local`, so I cut the arguments from the method. Let me know if I should keep it.

`nameof()` is also usable in constant contexts (eg. switch cases), so I added an override for `TryAsConstant()`.

Also a few l-values didn't have any nameof support, so I added it in this PR.

2024-01-11 04:31 UTC, Hinaichigo commented
When attempting to test this I get the following error:
`C:...OpenDream\DMCompiler\DM\Expressions\Dereference.cs(295,45): error CS0246: The type or namespace name 'NotNullWhen' could not be found (are you missing a using directive or an assembly reference?)`
I usually build OD using the `dotnet build` command, so maybe it's something that is normally included when you use an IDE like visual studio? Is there a workaround or some way to make it just werk with some kind of project setting?

2024-01-19 22:57 UTC, wixoaGit requested changes

2024-01-19 22:57 UTC, wixoaGit commented on DMCompiler/DM/Expressions/Builtins.cs
> +            if (_expr.GetNameof() is { } nameof) {
Instead of copy/pasting this code, it would be better to perform this once in the constructor and save the result in a `private string _nameof`.

2024-01-19 22:57 UTC, wixoaGit commented on DMCompiler/DM/Expressions/Builtins.cs
> +        }
This would be possible if it still had the `dmObject` argument

2024-01-19 22:57 UTC, wixoaGit commented on DMCompiler/DM/Expressions/Builtins.cs
> +        }
This would be possible if it still had the `proc` argument

2024-01-19 22:57 UTC, wixoaGit commented on DMCompiler/DM/Expressions/Dereference.cs
> +        public override bool TryAsConstant(out Constant constant) {
```suggestion
        public override bool TryAsConstant([NotNullWhen(true)] out Constant? constant) {
```

2024-01-19 22:57 UTC, wixoaGit commented on DMCompiler/DM/Expressions/LValue.cs
> -            return LocalVar.IsParameter ? proc.Parameters[LocalVar.Id] : proc.GetLocalVarName(LocalVar.Id);
This was the only use of `GetLocalVarName()`, that method should be removed

2024-01-20 04:27 UTC, wixoaGit commented on DMCompiler/DM/Expressions/Builtins.cs
> +            if (_expr.GetNameof() is { } nameof) {
Though feel free to ignore this if you're going to re-add the dmObject and proc args, since that wouldn't be possible.

2024-01-20 23:40 UTC, distributivgesetz commented
I'm going to move the eval of an expression name from the expression emission to the expression building phase, and if nothing depends on the existence of `Nameof` then I'm down to removing the class to return a constant string expression. `Nameof` a pretty bare class anyways and I don't feel like its existence justifies having to include context parameters into `TryAsConstant` (which is why I removed the parameters from `GetNameof`)

2024-01-21 17:32 UTC, distributivgesetz commented
> When attempting to test this I get the following error: `C:...OpenDream\DMCompiler\DM\Expressions\Dereference.cs(295,45): error CS0246: The type or namespace name 'NotNullWhen' could not be found (are you missing a using directive or an assembly reference?)`

Could be a problem with your RT submodule because the annotations package is referenced there. no idea otherwise.

2024-01-22 20:05 UTC, wixoaGit approved these changes

2024-01-22 20:05 UTC, merged