Remove description from rightclick menu
OpenDreamProject/OpenDream pull request #1703
Opened 2024-03-04 18:01 UTC by amylizzle

Is not BYOND parity. Is annoying on goon.

2024-03-04 19:02 UTC, wixoaGit commented
Would it be better to instead limit the width of the description text?

2024-03-04 20:43 UTC, amylizzle commented
I suppose you could, but I don't really know why it's still there since the things that need it have `examine` verbs now.

2024-03-06 02:56 UTC, wixoaGit requested changes

2024-03-06 02:56 UTC, wixoaGit commented on OpenDreamClient/Input/ContextMenu/VerbMenuPopup.xaml.cs
> +        Desc.Visible = false;
The Desc control should be removed from `VerbMenuPopup.xaml` rather than just hidden.

2024-03-06 22:20 UTC, wixoaGit approved these changes

2024-03-06 22:20 UTC, merged