Typemaker
OpenDreamProject/OpenDream pull request #1705
Opened 2024-03-04 18:28 UTC by ike709

Incorporates https://github.com/OpenDreamProject/OpenDream/pull/1696
Supercedes https://github.com/OpenDreamProject/OpenDream/pull/1220

Implements typechecking for procs and vars, controllable via pragmas. Currently it's a warning by default but we'll probably want to lower it to notice before merge since TG has a dozen or more issues due to how they use `as` currently (the uses don't actually do anything in BYOND).

2024-03-09 02:19 UTC, ike709 commented
Remind me to update the pragma wiki page when this is merged.

2024-03-11 07:07 UTC, wixoaGit requested changes

2024-03-11 07:07 UTC, wixoaGit commented on DMCompiler/DMStandard/_Standard.dm
> +proc/splicetext_char(Text, Start = 1, End = 0, Insert = "") as text
Same as `splicetext()`
```suggestion
proc/splicetext_char(Text, Start = 1, End = 0, Insert = "") as text|null
```

2024-03-11 07:07 UTC, wixoaGit commented on DMCompiler/DMStandard/_Standard.dm
> +proc/text2num(T, radix = 10) as num
This can return null if `T` is null
```suggestion
proc/text2num(T, radix = 10) as num|null
```

2024-03-11 07:07 UTC, wixoaGit commented on DMCompiler/DMStandard/_Standard.dm
> +proc/trimtext(Text) as text
This can return null if `Text` is invalid
```suggestion
proc/trimtext(Text) as text|null
```

2024-03-11 07:07 UTC, wixoaGit commented on DMCompiler/DMStandard/_Standard.dm
> +proc/turn(Dir, Angle) as num
This can also return /icon and /matrix

2024-03-11 07:07 UTC, wixoaGit commented on DMCompiler/DMStandard/_Standard.dm
> +proc/uppertext(T) as text
This just returns `T` if it's not text

2024-04-03 22:14 UTC, ike709 commented on DMCompiler/DM/Expressions/Constant.cs
> +        public override string ToString() {
If we encounter a `DMExpression` that doesn't handle typechecking properly, we print an error. This is an attempt to make certain expressions more readable/useful than printing the C# class name or whatever.

2024-04-03 22:15 UTC, ike709 commented on DMCompiler/DM/Expressions/Constant.cs
> -        /// </summary>
IDE goof

2024-04-05 19:29 UTC, ike709 commented on DMCompiler/DM/Builders/DMExpressionBuilder.cs
> +                var src = new Src(identifier.Location, dmObject.Path, dmObject.Path.GetATOMType());
```suggestion
                var src = new Src(identifier.Location, dmObject.Path);
```

2024-04-05 19:30 UTC, ike709 commented on DMCompiler/DM/Expressions/LValue.cs
> +        public override DMValueType ValType => (valType|DMValueType.Null); // src can and will get set to null by coders so del() doesn't kill an executing proc
```suggestion
    sealed class Src(Location location, DreamPath? path) : LValue(location, path) {
        public override DMValueType ValType => DMValueType.Anything; 
```

2024-04-09 01:44 UTC, wixoaGit commented on DMCompiler/DMStandard/_Standard.dm
> +proc/length(E) as num
I was suggesting the definition be removed since it parses to an AST node rather than a normal proc call.

2024-04-18 03:39 UTC, wixoaGit requested changes
Leaving myself notes of things to look at

2024-04-18 03:39 UTC, wixoaGit commented on DMCompiler/DM/Expressions/Builtins.cs
> +            var argumentInfo = arguments.EmitArguments(dmObject, proc, DMObjectTree.GetNewProc(pathInfo.Value.Id));
`pathInfo.Value.Id` can refer to a proc ID here rather than an object ID.

2024-04-18 03:39 UTC, wixoaGit commented on DMCompiler/DM/Expressions/Dereference.cs
> +        private DMComplexValueType? _valType;
This should not be set during expression emission

2024-04-18 03:39 UTC, wixoaGit commented on DMCompiler/DM/DMValueType.cs
> +        if (IsPath && type.IsPath && type.TypePath!.Value.IsDescendantOf(TypePath!.Value)) // Allow subtypes
Should use IsSubtypeOf

2024-04-18 03:39 UTC, wixoaGit commented on DMCompiler/DM/DMProc.cs
> +            return _astDefinition.Parameters;
`_parameters` should be used instead

2024-04-18 03:39 UTC, wixoaGit commented on DMCompiler/DM/DMObject.cs
> +    public DMComplexValueType? GetParentProcType(string name) {
We could maybe keep track of a proc's base definition instead?

2024-04-18 04:12 UTC, wixoaGit commented on DMCompiler/DM/Expressions/Dereference.cs
> +                    _valType = dmObject.GetVariable(fieldOperation.Identifier)?.ValType ?? DMValueType.Anything;
This tries to get the type from a var on the DMObject the proc is in rather than the thing actually being dereferenced

2024-04-18 04:12 UTC, wixoaGit commented on DMCompiler/DM/Expressions/Dereference.cs
>                  case IndexOperation indexOperation:
This doesn't set `_valType` so the type stays whatever was last dereferenced

2024-04-18 04:12 UTC, wixoaGit commented on DMCompiler/DM/Expressions/Dereference.cs
> +                    _valType = proc.ReturnTypes;
This sets the type to the return types of the current proc, rather than the dereferenced proc

2024-04-18 06:05 UTC, wixoaGit commented
I believe this is in a good enough spot. I'll let you make any last changes you want (like reducing the pragma's default error level or new unit tests) before merging.

2024-04-19 05:49 UTC, ike709 commented on DMCompiler/DMStandard/DefaultPragmaConfig.dm
> +#pragma LostTypeInfo warning
```suggestion
// NOTE: The next few pragmas are for OpenDream's experimental type checker
// This feature is still in development, elevating these pragmas outside of local testing is discouraged
// An RFC to finalize this feature is coming soon(TM)
// BEGIN TYPEMAKER
#pragma UnsupportedTypeCheck notice
#pragma InvalidReturnType notice
#pragma InvalidVarType notice
#pragma ImplicitNullType notice
#pragma LostTypeInfo notice
// END TYPEMAKER
```

2024-04-19 05:51 UTC, wixoaGit approved these changes

2024-04-19 06:02 UTC, merged