Lint for redundant positional arguments.
OpenDreamProject/OpenDream pull request #1770
Opened 2024-05-06 12:55 UTC by moonheart08

Fixes #1768, adds a new lint.

```
Warning OD2210 at code/modules/gamemaster/actions/atmos_leak.dm:20:45: The argument at index 1 is a positional argument with a redundant index (`1 = value` at argument 1). This does not function like a named argument and is likely a mistake.
Warning OD2210 at code/modules/gamemaster/actions/atmos_leak.dm:21:24: The argument at index 2 is a positional argument with a redundant index (`2 = value` at argument 2). This does not function like a named argument and is likely a mistake.
Warning OD2210 at code/modules/gamemaster/actions/atmos_leak.dm:22:21: The argument at index 3 is a positional argument with a redundant index (`3 = value` at argument 3). This does not function like a named argument and is likely a mistake.
```

2024-05-06 14:20 UTC, ike709 commented
Unit tests plz

2024-05-17 23:21 UTC, wixoaGit requested changes
I'd also like for there to be unit tests. You can make one by `#pragma`-ing the lint to an error and purposefully triggering it.

2024-05-17 23:21 UTC, wixoaGit commented on DMCompiler/DM/DMExpression.cs
> +
Unnecessary empty line
```suggestion
```

2024-05-17 23:21 UTC, wixoaGit commented on DMCompiler/DM/DMExpression.cs
> +        if ((!expr.ValType.IsAnything && !paramType.MatchesType(expr.ValType))) {
Unnecessary empty line & parenthesis
```suggestion
        if (!expr.ValType.IsAnything && !paramType.MatchesType(expr.ValType)) {
```

2024-05-17 23:21 UTC, wixoaGit commented on DMCompiler/DM/DMExpression.cs
> +                            $"The argument at index {argIndex + 1} is a positional argument with a redundant index (`{argIndex + 1} = value` at argument {argIndex + 1}). This does not function like a
We avoid using backticks in compiler messages due to it causing formatting issues when pasted elsewhere
```suggestion
                            $"The argument at index {argIndex + 1} is a positional argument with a redundant index (\"{argIndex + 1} = value\" at argument {argIndex + 1}). This does not function like a named argument and is likely a mistake.");
```

2024-07-11 02:56 UTC, wixoaGit approved these changes

2024-07-11 03:10 UTC, merged