Enable hot reloading of interface files
OpenDreamProject/OpenDream pull request #1779
Opened 2024-05-12 13:39 UTC by amylizzle

[Screencast from 2024-05-12 14-03-37.webm](https://github.com/OpenDreamProject/OpenDream/assets/3855802/d61cefc3-241a-4871-b904-463e9d656fd0)

Adds a new proc to `/world` `ODHotReloadInterface` which forces a reload of the cached interface file and notifies all connected clients to reload it. 

Note this also cleans up some stuff that would probably causes issues with reconnecting too, so that's a nice bonus.

2024-05-21 10:49 UTC, amylizzle reviewed
typo + using

2024-05-21 10:49 UTC, amylizzle commented on OpenDreamClient/Interface/DreamInterfaceManager.cs
> +using OpenToolkit.GraphicsLibraryFramework;
```suggestion
```

2024-05-21 10:49 UTC, amylizzle commented on TestGame/code.dm
> +		src << "tyring hot reload of interface..."
```suggestion
		src << "trying hot reload of interface..."
```

2024-06-07 14:54 UTC, amylizzle commented on OpenDreamRuntime/Procs/Native/DreamProcNativeWorld.cs
> +
```suggestion
```

2024-06-07 14:54 UTC, amylizzle commented on OpenDreamRuntime/Resources/DreamResourceManager.cs
> +                return resource;
```suggestion

                return resource;
```

2024-06-09 03:57 UTC, wixoaGit commented
I think it would be better to make this a server-side RT command

2024-06-09 04:01 UTC, wixoaGit requested changes
Linter seems to have missed these whitespace issues.

2024-06-09 04:01 UTC, wixoaGit commented on OpenDreamClient/Interface/DreamInterfaceManager.cs
> +        }
```suggestion
        }
        
```

2024-06-09 04:01 UTC, wixoaGit commented on OpenDreamClient/Interface/DreamInterfaceManager.cs
> +        //close popups if they're open
```suggestion
        
        //close popups if they're open
```

2024-06-09 04:01 UTC, wixoaGit commented on OpenDreamClient/Interface/DreamInterfaceManager.cs
> +        }
```suggestion
        }
        
```

2024-06-09 04:01 UTC, wixoaGit commented on OpenDreamRuntime/DreamManager.Connections.cs
> +            var msgLoadInterface = new MsgLoadInterface() {
```suggestion

            var msgLoadInterface = new MsgLoadInterface() {
```

2024-06-09 04:01 UTC, wixoaGit commented on OpenDreamRuntime/DreamManager.Connections.cs
> +            foreach (var connection in _connections.Values) {
```suggestion

            foreach (var connection in _connections.Values) {
```

2024-06-09 04:01 UTC, wixoaGit commented on OpenDreamRuntime/DreamManager.Connections.cs
> +
```suggestion
```

2024-06-09 09:16 UTC, amylizzle commented
> I think it would be better to make this a server-side RT command

I think it's actually better to leave this as a DM side action, so it can be easily integrated into existing admin and debug tooling which is pretty much all DM already.

The eventual plan here is to integrate it with hot reloading actions of IDEs, but until that's in place I think this is the best approach.

2024-06-09 16:32 UTC, wixoaGit commented
> > I think it would be better to make this a server-side RT command
> 
> I think it's actually better to leave this as a DM side action, so it can be easily integrated into existing admin and debug tooling which is pretty much all DM already.
> 
> The eventual plan here is to integrate it with hot reloading actions of IDEs, but until that's in place I think this is the best approach.

Can we get an RT command regardless so this can be used on codebases that haven’t added it?

2024-06-09 19:33 UTC, wixoaGit approved these changes

2024-06-09 19:33 UTC, merged