[HELP WANTED] Maybe(?) fixes(?) regex
OpenDreamProject/OpenDream pull request #1793
Opened 2024-05-16 05:44 UTC by Kapu1178

This pr is basically a shot in the dark. I believe that `regex.Find()` was broken when it was a global regex. Also impliments proper regex functionality for `findtext()` and `replacetext()`

2024-05-16 05:51 UTC, Kapu1178 reviewed
english

2024-05-16 05:51 UTC, Kapu1178 commented on DMCompiler/DMStandard/Types/Regex.dm
> +		set opendream_unimplimented = TRUE
```suggestion
		set opendream_unimplemented = TRUE
```

2024-05-16 05:51 UTC, Kapu1178 commented on DMCompiler/DMStandard/Types/Regex.dm
> +		set opendream_unimplimented = TRUE
```suggestion
		set opendream_unimplemented = TRUE
```

2024-05-17 23:10 UTC, wixoaGit requested changes

2024-05-17 23:10 UTC, wixoaGit commented on OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
> +                return DreamValue.True;
BYOND returns different values for different combinations of invalid arguments. Are those still replicated?

2024-11-15 06:04 UTC, wixoaGit commented
I am not sure what this was trying to fix, and it looks like this has been abandoned. I'll be closing this but feel free to reopen if you come back to it.

In either case I would like you to open an issue to report what bug you were trying to fix.

2024-11-15 06:04 UTC, closed without merging