Deduplicate github action logs
OpenDreamProject/OpenDream pull request #1796
Opened 2024-05-18 22:58 UTC by redmoogle

Deduplicate the logs

Fixes: #1778

would like a piece of code that would break on 1 of the os's to double check if fully works

2024-05-18 23:55 UTC, redmoogle commented
will do some testing on my fork later

2024-05-23 00:25 UTC, wixoaGit requested changes

2024-05-23 00:25 UTC, wixoaGit commented on .github/workflows/build-test.yml
> +      run: dotnet build --property WarningLevel=${{ matrix.os == 'ubuntu-latest' && '1' || '0' }} --configuration Release --no-restore /m
According to the [documentation](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/errors-warnings#warninglevel), the default value here is 4
```suggestion
      run: dotnet build --property WarningLevel=${{ matrix.os == 'ubuntu-latest' && '4' || '0' }} --configuration Release --no-restore /m
```

2024-05-23 00:36 UTC, wixoaGit commented
Another possible approach could be to use the `::remove-matcher` workflow command according to [this documentation](https://github.com/actions/toolkit/blob/main/docs/commands.md#problem-matchers). I think how it would be used here would be to do `echo "::remove-matcher owner=csc::"` on non-ubuntu runners.

2024-05-25 23:07 UTC, wixoaGit approved these changes

2024-05-25 23:07 UTC, merged