handles shrinking maxx/y
OpenDreamProject/OpenDream pull request #1798
Opened 2024-05-19 18:20 UTC by harryob

closes https://github.com/OpenDreamProject/OpenDream/issues/1688. apparently it is parity to grow and then shrink

2024-05-23 07:47 UTC, harryob commented on OpenDreamRuntime/DreamMapManager.cs
> +                            existingLevel.Grid.SetTile(new Vector2i(x, y), Tile.Empty);
this'll be addressed by https://github.com/OpenDreamProject/OpenDream/pull/1805

2024-06-21 23:46 UTC, wixoaGit requested changes

2024-06-21 23:46 UTC, wixoaGit commented on OpenDreamRuntime/DreamMapManager.cs
```suggestion
```

2024-06-21 23:46 UTC, wixoaGit commented on OpenDreamRuntime/DreamMapManager.cs
> +
```suggestion
```

2024-06-21 23:46 UTC, wixoaGit approved these changes

2024-06-22 00:02 UTC, merged