implement `/database` and `/database/query`
OpenDreamProject/OpenDream pull request #1802
Opened 2024-05-21 15:31 UTC by harryob

2024-07-23 00:51 UTC, wixoaGit requested changes

2024-07-23 00:51 UTC, wixoaGit commented on OpenDreamRuntime/Objects/Types/DreamObjectDatabaseQuery.cs
> +    }
```suggestion
    }
```

2024-07-23 00:51 UTC, wixoaGit commented on OpenDreamRuntime/Objects/Types/DreamObjectDatabaseQuery.cs
> +
```suggestion
        for (var i = 0; i < values.Length; i++) {
```

2024-07-23 00:51 UTC, wixoaGit commented on OpenDreamRuntime/Objects/Types/DreamObjectDatabaseQuery.cs
> +                    break;
```suggestion
                    }
                    
                    break;
```

2024-07-23 00:51 UTC, wixoaGit commented on OpenDreamRuntime/Objects/Types/DreamObjectDatabaseQuery.cs
> +                    break;
```suggestion
                    }
                    
                    break;
```

2024-07-23 00:51 UTC, wixoaGit commented on OpenDreamRuntime/Objects/Types/DreamObjectDatabaseQuery.cs
> +
```suggestion
            }
```

2024-07-23 00:51 UTC, wixoaGit commented on OpenDreamRuntime/Objects/Types/DreamObjectDatabaseQuery.cs
> +    }
```suggestion
    }
```

2024-07-23 00:51 UTC, wixoaGit commented on OpenDreamRuntime/Objects/Types/DreamObjectDatabaseQuery.cs
> +    }
```suggestion
    }
```

2024-07-23 00:51 UTC, wixoaGit commented on OpenDreamRuntime/Objects/Types/DreamObjectDatabaseQuery.cs
> +        ClearCommand();
```suggestion
        }
        
        ClearCommand();
```

2024-07-23 00:51 UTC, wixoaGit commented on OpenDreamRuntime/Objects/Types/DreamObjectDatabaseQuery.cs
> +
```suggestion
    private static string ParseCommandText(string text) {
```

2024-07-23 00:51 UTC, wixoaGit commented on OpenDreamRuntime/Objects/Types/DreamObjectDatabaseQuery.cs
> +            {
```suggestion
            switch (character) {
```

2024-07-23 00:53 UTC, wixoaGit commented on OpenDreamRuntime/Procs/Native/DreamProcNativeDatabaseQuery.cs
> +    [DreamProc("Add")]
```suggestion
internal static class DreamProcNativeDatabaseQuery {
    [DreamProc("Add")]
```

2024-07-23 00:53 UTC, wixoaGit commented on OpenDreamRuntime/Procs/Native/DreamProcNativeDatabaseQuery.cs
> +    }
```suggestion
        return new DreamValue(list);
    }
```

2024-07-23 00:54 UTC, wixoaGit commented on OpenDreamRuntime/Procs/Native/DreamProcNativeDatabaseQuery.cs
> +    }
```suggestion
        return new DreamValue(list);
    }
```

2024-07-23 00:56 UTC, wixoaGit commented on OpenDreamRuntime/Objects/Types/DreamObjectDatabaseQuery.cs
> +        var newString = new StringBuilder();
```suggestion
    private static string ParseCommandText(string text) {
        var newString = new StringBuilder();
```

2024-08-05 11:29 UTC, harryob commented on OpenDreamRuntime/Objects/Types/DreamObjectDatabase.cs
> +        _connection = new SqliteConnection($"Data Source={filename};Mode=ReadWriteCreate");
that's a silly one - addressed!

2024-08-19 18:23 UTC, wixoaGit approved these changes

2024-08-19 18:23 UTC, merged