Handle `fexists()` in the preprocessor
OpenDreamProject/OpenDream pull request #1824
Opened 2024-06-02 03:17 UTC by ike709

Fixes #1821

2024-06-02 03:20 UTC, ike709 commented on Content.Tests/DMProject/Tests/Preprocessor/fexists_fail.dm
> +#error "it doesn't exist, yay"
```suggestion
#if fexists("fake/path.abc")
#error "how could this exist"

```

2024-06-02 03:20 UTC, ike709 commented on Content.Tests/DMProject/Tests/Preprocessor/fexists_fail.dm
> +
```suggestion
```

2024-06-02 03:21 UTC, ike709 commented on DMCompiler/Compiler/DMPreprocessor/DMPreprocessorParser.cs
> +                        DMCompiler.Emit(WarningCode.DefinedMissingParen, token.Location,
Didn't seem worth adding a second warning code.

2024-06-02 03:22 UTC, ike709 commented on DMCompiler/Compiler/DMPreprocessor/DMPreprocessorParser.cs
> +                    Console.WriteLine(Directory.GetCurrentDirectory());
```suggestion
```

2024-06-02 21:58 UTC, wixoaGit requested changes

2024-06-02 21:58 UTC, wixoaGit commented on DMCompiler/Compiler/DMPreprocessor/DMPreprocessorParser.cs
> +                else if (token.Text == "fexists") {
```suggestion
                } else if (token.Text == "fexists") {
```

2024-06-02 21:58 UTC, wixoaGit commented on DMCompiler/Compiler/DMPreprocessor/DMPreprocessorParser.cs
> +                        Error($"Unexpected token {fexistsInner.PrintableText} - resource path expected");
`#if fexists()` doesn't take a resource path as an argument.
```suggestion
                    if (fexistsInner.Type != TokenType.DM_ConstantString) {
                        Error($"Unexpected token {fexistsInner.PrintableText} - file path expected");
```

2024-06-02 21:58 UTC, wixoaGit commented on DMCompiler/Compiler/DMPreprocessor/DMPreprocessorParser.cs
> +                    Token fexistsInner = Current();
Rename to `fExistsInner`

2024-06-02 21:58 UTC, wixoaGit commented on DMCompiler/Compiler/DMPreprocessor/DMPreprocessorParser.cs
> +
```suggestion
```

2024-06-02 21:58 UTC, wixoaGit commented on DMCompiler/Compiler/DMPreprocessor/DMPreprocessorParser.cs
> +                    var filePath = Path.GetRelativePath(".", fexistsInner.Value.ToString().Replace('\\', '/'));
We ensure this is a `DM_ConstantString` token earlier, which should always have a value.
```suggestion
                    var filePath = Path.GetRelativePath(".", fexistsInner.Value!.ToString().Replace('\\', '/'));
```

2024-06-02 21:58 UTC, wixoaGit commented on DMCompiler/Compiler/DMPreprocessor/DMPreprocessorParser.cs
> +                    var outputDir = Path.GetDirectoryName(DMCompiler.Settings.Files?[0]) ?? "/";
In BYOND `#if fexists()` is relative to the current file and not the root of the project.

2024-06-02 21:58 UTC, wixoaGit commented on DMCompiler/Compiler/DMPreprocessor/DMPreprocessorParser.cs
> +                    return meep;
```suggestion
                    return File.Exists(filePath) ? 1.0f : 0.0f;
```

2024-06-07 00:05 UTC, wixoaGit approved these changes

2024-06-07 00:17 UTC, merged