Implements `winget()` formatting
OpenDreamProject/OpenDream pull request #1898
Opened 2024-07-21 13:48 UTC by amylizzle

So apparently BYOND just loves being grossly inconsistent, and `winget()` calls act differently to embedded wingets.

This fixes that, and incidentally enables darkmode on goon as a side-effect
![image](https://github.com/user-attachments/assets/640bf441-abb4-4219-a1f6-6d51141ca7db)

2024-07-22 19:50 UTC, wixoaGit requested changes

2024-07-22 19:50 UTC, wixoaGit commented on OpenDreamClient/Interface/DMF/IDMFProperty.cs
> +    public string AsSnowflake();
Can we get a documentation comment on this? The name itself isn't very descriptive.

2024-07-22 19:50 UTC, wixoaGit commented on OpenDreamClient/Interface/DMF/IDMFProperty.cs
>      public override string ToString() {
```suggestion
    }
    
    public override string ToString() {
```

2024-07-22 19:50 UTC, wixoaGit commented on OpenDreamClient/Interface/DMF/IDMFProperty.cs
>      public override string ToString() {
```suggestion
    }
    
    public override string ToString() {
```

2024-07-22 19:50 UTC, wixoaGit commented on OpenDreamClient/Interface/DMF/IDMFProperty.cs
>      public override string ToString() {
```suggestion
    }
    
    public override string ToString() {
```

2024-07-23 09:52 UTC, amylizzle commented on OpenDreamClient/Interface/DMF/IDMFProperty.cs
> +    public string AsSnowflake();
```suggestion
    /// winget() calls do not act the same as embedded winget calls, and the default behaviour is some whacky combination of AsEscaped() and AsRaw(). This proc handles that. Fucking BYOND.
    public string AsSnowflake();
```

2024-07-23 21:24 UTC, wixoaGit requested changes

2024-07-23 21:24 UTC, wixoaGit commented on OpenDreamClient/Interface/DMF/IDMFProperty.cs
> +    /// winget() calls do not act the same as embedded winget calls, and the default behaviour is some whacky combination of AsEscaped() and AsRaw(). This proc handles that. Fucking BYOND.
```suggestion
    public string AsRaw();
    
    /// winget() calls do not act the same as embedded winget calls, and the default behaviour is some whacky combination of AsEscaped() and AsRaw(). This proc handles that. Fucking BYOND.
```

2024-07-23 21:24 UTC, wixoaGit approved these changes

2024-07-23 21:40 UTC, merged