Implement `walk()` and `walk_rand()`
OpenDreamProject/OpenDream pull request #1906
Opened 2024-08-05 21:22 UTC by ike709

- Implemented `walk()`. Including `walk(Ref, 0)` to cease any walking.
- Implemented `walk_rand()`
- Added a helper for getting a random dir
- Added a `GetStep()` overload that takes dir as an integer directly, to avoid redundant casting.
- `speed` is now ignored in WalkManager, rather than the native walk-related procs

https://github.com/user-attachments/assets/dd802c99-afa4-4720-950f-c68563211b53

2024-08-05 21:30 UTC, ike709 commented on OpenDreamRuntime/WalkManager.cs
> +        DreamThread.Run($"walk_rand", async state => {
```suggestion
        DreamThread.Run("walk_rand", async state => {
```

2024-08-06 10:51 UTC, amylizzle commented on OpenDreamRuntime/Procs/Native/DreamProcNativeHelpers.cs
> +        AtomDirection[] dirs = [
should this not be a static const outside the proc def? idk if C# is smart enough to not redefine the list every time the proc is called

2024-08-08 02:49 UTC, wixoaGit requested changes

2024-08-08 02:49 UTC, wixoaGit commented on OpenDreamRuntime/Procs/Native/DreamProcNativeHelpers.cs
> +    public static DreamObjectTurf? GetStep(AtomManager atomManager, IDreamMapManager mapManager, DreamObjectAtom loc, int dirInt) {
Probably better to have the calling code cast the dir to an AtomDirection instead of creating a version of this method that takes an int.

2024-08-08 02:49 UTC, wixoaGit commented on OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
> +            bundle.GetArgument(3, "Speed").TryGetValueAsInteger(out var speed);
```suggestion
            bundle.GetArgument(1, "Lag").TryGetValueAsInteger(out var lag);
            bundle.GetArgument(2, "Speed").TryGetValueAsInteger(out var speed);
```

2024-08-08 17:25 UTC, ike709 commented on DMCompiler/DMStandard/_Standard.dm
> +	set opendream_unimplemented = TRUE
```suggestion
	set opendream_unimplemented = 1
```

2024-08-08 22:00 UTC, wixoaGit approved these changes

2024-08-08 22:00 UTC, merged