Convert DreamValue.cs to file-scoped namespace
OpenDreamProject/OpenDream pull request #1924
Opened 2024-08-15 08:32 UTC by TheTyrant25

Same reasoning and method as #1922, it gets rid of a warning and an indent.

2024-08-15 10:31 UTC, TheTyrant25 commented
those should all be pre existing issues

2024-08-19 18:56 UTC, wixoaGit requested changes

2024-08-19 18:56 UTC, wixoaGit commented on OpenDreamRuntime/DreamValue.cs
> +namespace OpenDreamRuntime;
```suggestion
namespace OpenDreamRuntime;

```

2024-08-19 18:56 UTC, wixoaGit approved these changes

2024-08-19 19:10 UTC, merged