Handle `var/foo[]= value` in proc statements
OpenDreamProject/OpenDream pull request #1984
Opened 2024-09-23 06:03 UTC by ike709

Apparently we already handled this case in `DefinitionParameter()` so I just copied what we were doing there.

2024-09-23 06:12 UTC, ike709 commented on Content.Tests/DMProject/Tests/List/DoubleSquareBracketEquals.dm
> +	var/foo[] = new()
```suggestion
	var/foo[]=new()
```

2024-10-03 04:03 UTC, wixoaGit requested changes

2024-10-03 04:03 UTC, wixoaGit commented on DMCompiler/Compiler/DM/DMParser.cs
> +                    } else if (Check(TokenType.DM_DoubleSquareBracketEquals)) {
Shouldn't this also have the doubly-initialized warning that the above has?

2024-10-05 17:51 UTC, wixoaGit approved these changes

2024-10-05 17:52 UTC, merged