Halves `OpenDreamClient` warnings
OpenDreamProject/OpenDream pull request #2032
Opened 2024-10-15 03:25 UTC by ike709

Takes `OpenDreamClient` from 40 to 20 warnings.

I confirmed that the changes to gliding and the context menu didn't break them.

2024-10-15 04:06 UTC, ike709 commented on OpenDreamClient/Interface/InterfaceElement.cs
> +            if(descriptor is null) throw new NullReferenceException(); // We're in a try/catch anyway, just play it safe
I think complying with this results in yuckier-looking code in this case so I'll leave it to wixoa to decide.

2024-10-24 20:00 UTC, wixoaGit requested changes

2024-10-24 20:00 UTC, wixoaGit commented on OpenDreamClient/Interface/DreamInterfaceManager.cs
> +        // Note: Id has a getter to ensure Id.Value is never null
I don't see why `Value` is marked nullable in the first place. The value isn't nullable in the constructor, and nothing ever gives it `null`.

2024-10-24 20:00 UTC, wixoaGit commented on OpenDreamClient/Interface/DMF/IDMFProperty.cs
> +    public bool Equals(DMFPropertyVec2 other)
All these new methods need their braces moved to the same line.

2024-10-24 20:00 UTC, wixoaGit commented on OpenDreamClient/Interface/DMF/IDMFProperty.cs
> +    }
Move these to the bottom

2024-10-24 20:00 UTC, wixoaGit commented on OpenDreamClient/Interface/DMF/IDMFProperty.cs
> +    }
Move these to the bottom

2024-10-24 20:00 UTC, wixoaGit commented on OpenDreamClient/Interface/InterfaceElement.cs
> +            if(descriptor is null) throw new NullReferenceException(); // We're in a try/catch anyway, just play it safe
I'm fine with it as is.

2024-10-30 02:51 UTC, wixoaGit approved these changes

2024-10-30 02:51 UTC, merged