Apply UIScale to ControlWindow size
OpenDreamProject/OpenDream pull request #2045
Opened 2024-10-18 17:20 UTC by ike709

Fixes the size of various UIs like TG's Say popup.

2024-10-19 23:54 UTC, wixoaGit requested changes

2024-10-19 23:54 UTC, wixoaGit commented on OpenDreamClient/Interface/Controls/ControlWindow.cs
> +                    size.X = (int)(size.X * uiScale);
This is probably something better left for RT to do automatically, but we can just TODO that
```suggestion
                    size.X = (int)(size.X * uiScale); // TODO: RT should probably do this itself
```

2024-10-19 23:54 UTC, wixoaGit commented on OpenDreamClient/Interface/Controls/ControlWindow.cs
> +                    var uiScale = _configurationManager.GetCVar(CVars.DisplayUIScale);
A few different things can affect the UI scale. This CVar is actually 0 by default, to indicate using your OS settings.
```suggestion
                    var uiScale = _myWindow.osWindow.UIScale;
```

2024-10-20 00:02 UTC, ike709 commented on OpenDreamClient/Interface/Controls/ControlWindow.cs
> +    [Dependency] private readonly IConfigurationManager _configurationManager = default!;
```suggestion

namespace OpenDreamClient.Interface.Controls;

public sealed class ControlWindow : InterfaceControl {
    [Dependency] private readonly IClyde _clyde = default!;
    [Dependency] private readonly IUserInterfaceManager _uiMgr = default!;
```

2024-10-20 00:02 UTC, wixoaGit approved these changes

2024-10-20 00:09 UTC, merged