Peephole optimizer & proc decoder fixes
OpenDreamProject/OpenDream pull request #2054
Opened 2024-10-21 02:44 UTC by ike709

This PR does a few things:

1. Fixes peephole optimizations not being applied to opcodes created by peephole optimizations. E.g.:
`PushNull -> Assign -> Pop` was being optimized to `PushNull -> AssignPop`, but the optimizer offset wasn't rolled back far enough to consider optimizing `PushNull -> AssignPop` to `NullRef`. It would only be rolled back to the new `AssignPop` opcode. This meant that the `NullRef` opcode was never used, which is now fixed.

2. Fixes a few opcodes not being implemented in `ProcDecoder`. Because a few opcodes were specific to optimizations that were never applied, they never triggered any errors in the disassembler. `DreamProcOpcode.NullRef` and `DreamProcOpcode.PushNOfStringFloats` can now be decoded.

3. Fixes `PushNOfStringFloats` only being applied to pairs of `StringFloat`s. Because of how the peephole optimizer works, it would (now that it actually runs) try to run the `PushNOfStringFloats` optimization before every `PushString` and `PushFloat` in the sequence had been converted to `StringFloat`s. The `PushNOfStringFloat`s optimization has been folded into the `StringFloat` optimization, and it'll just use the relevant opcode depending on how many pairs of `PushString` and `PushFloat` opcodes there are. This has the added benefit of reducing the amount of optimizations that need to be applied.

We really need to implement a system for unit testing the peephole optimizer on input bytecode, but that is out of scope for this PR.

2024-10-21 02:58 UTC, ike709 commented on DMCompiler/Optimizer/PeepholeOptimizations.cs
> +        List<IAnnotatedBytecode> args = new List<IAnnotatedBytecode>(2 * count + 1);
```suggestion
        List<IAnnotatedBytecode> args = new List<IAnnotatedBytecode>(2 * count + 1) { new AnnotatedBytecodeInteger(count, input[index].GetLocation()) };
```

2024-10-21 03:02 UTC, ike709 commented on DMCompiler/Optimizer/PeepholeOptimizations.cs
> +        args.Add(new AnnotatedBytecodeInteger(count, input[index].GetLocation()));
```suggestion
```

2024-10-28 04:55 UTC, wixoaGit requested changes

2024-10-28 04:55 UTC, wixoaGit commented on DMCompiler/Optimizer/PeepholeOptimizations.cs
> +            stackDelta += 2;
None of these args are pushed to the stack and so shouldn't have an effect on the stack.

2024-10-28 13:17 UTC, wixoaGit commented on DMCompiler/Optimizer/PeepholeOptimizations.cs
> +            stackDelta += 2;
Turns out an opcode starting with `Push...` does indeed push

2024-10-28 13:27 UTC, wixoaGit approved these changes

2024-10-28 13:27 UTC, merged