String concat const folding
OpenDreamProject/OpenDream pull request #2061
Opened 2024-10-25 20:15 UTC by ike709

Moves string concat const folding from DMASTFolder to the peephole optimizer.

Not super useful until https://github.com/OpenDreamProject/OpenDream/issues/2059 is resolved

2024-11-16 01:08 UTC, ike709 commented on DMCompiler/Optimizer/PeepholeOptimizations.cs
> +        var combinedId = DMObjectTree.AddString(firstString.ResolveString() + secondString.ResolveString());
```suggestion
        var combinedId = DMObjectTree.AddString(firstString.ResolveString() + secondString.ResolveString()); // TODO: Currently doesn't handle removing strings from the string tree that have no other references
```

2024-11-16 15:17 UTC, ike709 commented on DMCompiler/Optimizer/PeepholeOptimizations.cs
> +    public void Apply(List<IAnnotatedBytecode> input, int index) {
```suggestion
    public void Apply(DMCompiler compiler, List<IAnnotatedBytecode> input, int index) {
```

2024-11-17 02:14 UTC, wixoaGit requested changes

2024-11-17 02:14 UTC, wixoaGit commented on DMCompiler/Optimizer/PeepholeOptimizations.cs
> +using DMCompiler.DM;
```suggestion
```

2024-11-17 02:14 UTC, wixoaGit approved these changes

2024-11-17 02:21 UTC, merged