Adds a system for printing stats to the disassembler
OpenDreamProject/OpenDream pull request #2067
Opened 2024-10-27 21:59 UTC by ike709

This adds a `stats` command to the disassembler which can be extended to provide various info about the bytecode. For now I've added a `procs-by-type` argument which prints the number of proc declarations on each type in descending order.

I've also spruced up the `help` command with the ability to take a `command` argument to learn more about a specific command.

2024-10-27 22:04 UTC, ike709 commented on DMDisassembler/Program.cs
> +                    Console.WriteLine($"Command \"{command}\" takes 0 or 1 arguments.");
```suggestion
                    Console.WriteLine($"Command \"{command}\" takes 0 or 1 arguments. Ignoring extra arguments.");
```

2024-10-27 22:05 UTC, ike709 commented on DMDisassembler/Program.cs
> +                if (pair.Key == 0) {
Gross.

2024-10-27 22:05 UTC, ike709 commented on DMDisassembler/Program.cs
> +            for (int i = 0; i < sorted.Count; i++) {
Not when we need to handle changing `/` to `<global>` for Root.

2024-10-27 22:06 UTC, ike709 commented on DMDisassembler/Program.cs
> +    public static List<DMType> TypesById = null;
Consistent with the rest of the code.

2024-10-27 22:17 UTC, ike709 commented on DMDisassembler/Program.cs
> +            for (int i = 0; i < sorted.Count; i++) {
Meh...?

2024-12-11 23:02 UTC, wixoaGit requested changes

2024-12-11 23:02 UTC, wixoaGit commented on DMDisassembler/Program.cs
> +                var pair = sorted[i];
You can avoid the large & slow list creation
```suggestion
            Console.WriteLine("Type: Proc Declarations");
            foreach (var pair in typeIdToProcCount.OrderByDescending(kvp => kvp.Value)) {
```

2024-12-11 23:02 UTC, wixoaGit commented on DMDisassembler/Program.cs
> +            Console.WriteLine("quit|q                    : Exits the disassembler");
```suggestion
            Console.WriteLine("exit|quit|q               : Exits the disassembler");
```

2024-12-11 23:07 UTC, wixoaGit approved these changes

2024-12-11 23:12 UTC, merged