Use a `switch` in `ProcStatement()`
OpenDreamProject/OpenDream pull request #2073
Opened 2024-11-01 00:23 UTC by ike709

Doesn't really impact compiletime either way, but it means we no longer have to worry about the order we're parsing proc statements.

2024-11-13 05:09 UTC, wixoaGit commented
> Doesn't really impact compiletime either way, but it means we no longer have to worry about the order we're parsing proc statements.

Did we ever have to worry about it if it doesn't impact compile time?

2024-11-13 11:54 UTC, ike709 commented
> Did we ever have to worry about it if it doesn't impact compile time?

The order of proc statements in the original code did have a measurable impact on compile time (at least back when I first rearranged them based on frequency, dunno about current year).

2024-11-15 23:17 UTC, wixoaGit requested changes

2024-11-15 23:17 UTC, wixoaGit commented on DMCompiler/Compiler/DM/DMParser.cs
> +                }
I think a switch expression is a better fit here, readability wise
```suggestion
                DMASTProcStatement? procStatement = Current().Type switch {
                    TokenType.DM_If => If(),
                    TokenType.DM_Return => Return(),
                    TokenType.DM_For => For(),
                    TokenType.DM_Set => Set(),
                    TokenType.DM_Switch => Switch(),
                    TokenType.DM_Continue => Continue(),
                    TokenType.DM_Break => Break(),
                    TokenType.DM_Spawn => Spawn(),
                    TokenType.DM_While => While(),
                    TokenType.DM_Do => DoWhile(),
                    TokenType.DM_Throw => Throw(),
                    TokenType.DM_Del => Del(),
                    TokenType.DM_Try => TryCatch(),
                    TokenType.DM_Goto => Goto(),
                    TokenType.DM_Slash or TokenType.DM_Var => ProcVarDeclaration(),
                    _ => null
                };
```

2024-11-16 02:25 UTC, wixoaGit approved these changes

2024-11-16 02:25 UTC, merged