Basic Maptext
OpenDreamProject/OpenDream pull request #2108
Opened 2024-11-23 17:48 UTC by amylizzle

Rudimentary implementation. No tag processing but it shouldn't be too hard to add (just copying richtext formatting stuff)

Maptext inherits filters and transforms from parent atom.

2024-12-24 00:21 UTC, amylizzle commented on OpenDreamClient/Rendering/DreamViewOverlay.cs
> +    [Dependency] private readonly IResourceCache _resourceCache = default!;
this is not the style, shush lint

2024-12-24 00:21 UTC, amylizzle commented on OpenDreamShared/Dream/IconAppearance.cs
> +        hashCode.Add(Maptext);
dum

2024-12-24 00:21 UTC, amylizzle commented on OpenDreamShared/Dream/IconAppearance.cs
> +        hashCode.Add(MaptextSize);
stoopid

2025-01-19 06:55 UTC, wixoaGit requested changes

2025-01-19 06:56 UTC, wixoaGit approved these changes

2025-01-19 07:03 UTC, merged