Implements filters
OpenDreamProject/OpenDream pull request #798
Opened 2022-09-19 16:18 UTC by amylizzle

Fixes #294 by implementing `filter()` and supporting cast.

- [ ] Implement `/filter` type
- [ ] Add shader for outline
- [ ] Implement basic shader processing in `UpdateAppearance()`
- [ ] All the other shaders

2022-10-01 23:09 UTC, Altoids1 commented
This PR is ridiculous and I am so happy someone else handled this nonsense for us, thanks a bunch

2022-10-06 09:47 UTC, amylizzle commented
TODO: change this to `/dm_filter`, the ENTIRELY UNDOCUMENTED type path of filters in DM

2022-10-30 19:02 UTC, wixoaGit requested changes

2022-10-30 19:02 UTC, wixoaGit commented on OpenDreamShared/Dream/DreamFilter.cs
> +        [ViewVariables] public float? filter_falloff = null;
All these vars end up with lots of verbose & repeated code. Would it be possible to instead have a dictionary of keys/values for shader parameters?

2022-11-26 01:05 UTC, wixoaGit approved these changes

2022-11-26 01:08 UTC, merged