Fixes `typesof()` for non-paths
OpenDreamProject/OpenDream pull request #813
Opened 2022-09-24 22:56 UTC by ike709

Replicates BYOND behavior

2022-09-28 15:11 UTC, wixoaGit requested changes

2022-09-28 15:11 UTC, wixoaGit commented on OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
> +                if (!type.TryGetValueAsPath(out var typePath)) {
This proc also accepts DreamObjects

2022-09-29 15:30 UTC, wixoaGit commented on OpenDreamRuntime/Procs/Native/DreamProcNativeRoot.cs
> +                if (!type.TryGetValueAsPath(out var typePath)) {
This proc apparently also takes strings like `"/obj"`. DreamLists need to be ignored too.

2022-10-02 22:29 UTC, ike709 commented
It's not as optimal as possible but it should work.

2022-10-04 23:45 UTC, out-of-phaze commented
It doesn't work for things like `typesof("/datum/proc")`. Which works in DM, for some absurd reason! Gives a list of all procs defined on datum.

2022-10-05 17:31 UTC, out-of-phaze commented
> Separate issue, out of scope :^)

I literally gave you a patch that solves it

2022-10-05 17:36 UTC, ike709 commented
I commented that _before_ you did :^)

2022-11-13 02:23 UTC, SpaceManiac approved these changes

2022-11-13 02:35 UTC, merged