Support const-eval for `==` and `!=`
OpenDreamProject/OpenDream pull request #834
Opened 2022-10-01 20:31 UTC by ike709

2022-10-01 20:31 UTC, ike709 commented on DMCompiler/DM/Expressions/Constant.cs
> +using Robust.Shared.Localization;
```suggestion
```

2022-10-01 20:35 UTC, Altoids1 commented on DMCompiler/DM/Expressions/Constant.cs
> +using Robust.Shared.Localization;
what

2022-10-01 20:50 UTC, ike709 commented on DMCompiler/DM/Expressions/Constant.cs
> +        }
```suggestion
        public override Constant Equals(Constant rhs) {
            if (rhs is not Number rhsNum || !MathHelper.CloseTo(rhsNum.Value, Value)) {
                return new Number(Location, 0); // false
            }

            return new Number(Location, 1); // true
        }

        public override Constant NotEquals(Constant rhs) {
            if (rhs is not Number rhsNum || MathHelper.CloseTo(rhsNum.Value, Value)) {
                return new Number(Location, 1); // true
            }

            return new Number(Location, 0); // false
        }
```

2022-10-01 23:01 UTC, Altoids1 commented
No longer a dependency of the preproc PR (but you should merge it anyways since Ike was very nice to do this for me)

2022-10-11 04:22 UTC, wixoaGit requested changes

2022-10-11 04:22 UTC, wixoaGit commented on DMCompiler/DM/Expressions/Binary.cs
> +            constant = lhs.NotEquals(rhs);
Would there ever a case where `NotEquals()` isn't just `!Equals()`?

2022-10-11 04:42 UTC, wixoaGit commented on DMCompiler/DM/Expressions/Binary.cs
> +            constant = lhs.NotEquals(rhs);
Might just be able to use `IsTruthy()` for this too.

2022-10-29 18:12 UTC, ike709 commented
That's what I get for trying to webedit.

2022-10-29 23:10 UTC, Altoids1 commented
Eclipsed by #885.

2022-10-30 03:03 UTC, closed without merging