Implement `%%` and `%%=`
OpenDreamProject/OpenDream pull request #870
Opened 2022-10-26 00:43 UTC by ike709

Fixes #853 

Not tested in the slightest because I finished it as soon as class ended.

2022-10-28 20:11 UTC, ZeWaka commented
Requires #883

2022-10-28 20:20 UTC, ike709 commented
No it doesn't, this won't impact 514 codebases at all.

2022-11-15 02:45 UTC, wixoaGit requested changes

2022-11-15 02:45 UTC, wixoaGit commented on Content.Tests/DMProject/Tests/Operators/modulo_modulo.dm
> +	ASSERT(A == 1.2001398)
Both these assertions fail on BYOND

2022-11-15 02:45 UTC, wixoaGit commented on DMCompiler/DM/Expressions/Constant.cs
> +                return base.Add(rhs);
This probably means to call `base.ModuloMudulo()`

..So does every other math operation override that seems to have copy-pasted `base.Add()`
```suggestion
                return base.ModuloModulo(rhs);
```

2022-11-15 02:45 UTC, wixoaGit commented on DMCompiler/DM/Visitors/DMVisitorExpression.cs
> +            var rhs = DMExpression.Create(_dmObject, _proc, modulusModulusAssign.B);
You can do `a %%= new`
```suggestion
            var lhs = DMExpression.Create(_dmObject, _proc, modulusModulusAssign.A, _inferredPath);
            var rhs = DMExpression.Create(_dmObject, _proc, modulusModulusAssign.B, lhs.Path);
```

2022-11-15 02:45 UTC, wixoaGit commented on OpenDreamRuntime/Procs/DMOpcodeHandlers.cs
> +            }
`ModulusModulusValues()` already does the type check and exception
```suggestion
            state.Push(ModulusModulusValues(first, second));
```

2022-11-15 03:24 UTC, ike709 commented on Content.Tests/DMProject/Tests/Operators/modulo_modulo.dm
> +
```suggestion
// BREAKING CHANGE: The floating point precision is slightly different between OD and BYOND, giving slightly different values
```

2022-11-15 03:25 UTC, ike709 commented on OpenDreamRuntime/Procs/DMOpcodeHandlers.cs
> +                // BYOND docs say that A %% B is equivalent to B * fract(A/B)
```suggestion
                // BYOND docs say that A %% B is equivalent to B * fract(A/B)
                // BREAKING CHANGE: The floating point precision is slightly different between OD and BYOND, giving slightly different values
```

2022-11-15 03:26 UTC, wixoaGit approved these changes

2022-11-15 03:32 UTC, merged