Add debug adapter server
OpenDreamProject/OpenDream pull request #889
Opened 2022-10-30 04:24 UTC by SpaceManiac

Client: https://github.com/SpaceManiac/vscode-opendream
* Provides combined DM+C# debugging if your DM project and OpenDream checkout are both opened in a workspace together
* Otherwise allows you to configure a path to your OpenDream checkout and uses it in the background

Implemented:
* Show `world.log` output in debug console
* Function breakpoints
* Break on exception
* Pause
* Continue
* Rudimentary threads, stack frames, scopes, and variables

Future work:
* Step in, step over, step out
* Line breakpoints

Architecture changes:
* DreamThread has a Name attribute
* Compiled `.json` includes source and line information for each proc's header
* ProcScheduler keeps track of sleeping procs so they can be discovered by the debugger

2022-10-30 04:34 UTC, ike709 commented
Holy crap

2022-10-30 05:09 UTC, Altoids1 commented
Wow!!

2022-11-01 21:52 UTC, wixoaGit requested changes

2022-11-02 00:54 UTC, SpaceManiac commented on OpenDreamRuntime/Procs/DebugAdapter/DebugAdapterClient.cs
> +        while (_client.Connected && (_netStream.DataAvailable || _client.Available > 0 || _netReader.Peek() != -1)) {
`_netStream.DataAvailable` goes to false as soon as there is one Read call. `_client.Available` and `_netReader` each keep buffers and we have to loop until they are all drained.

2022-11-02 00:57 UTC, SpaceManiac commented on OpenDreamRuntime/Procs/DebugAdapter/DebugAdapterClient.cs
> +        _sawmill.Debug($"Sending {body.Length} {body}");
Switched to Verbose which is hidden by default, though I suppose they could also be totally removed

2022-11-02 01:18 UTC, wixoaGit approved these changes

2022-11-02 01:18 UTC, merged