Implements compiler configuration through new preproc directive: `#pragma`
OpenDreamProject/OpenDream pull request #896
Opened 2022-11-03 19:52 UTC by Altoids1

![image](https://user-images.githubusercontent.com/29939414/202064297-d0a59359-db7b-4c00-a853-c9b23dd52aa1.png)

## Summary
The syntax for `#pragma` that I am going with is probably `#pragma errorName Value`, where errorName can be either the error code or enum name for the error code, and Value is either `disabled`, `notice`, `warning`, or `error`.

This will allow us to vary the behaviour of the compiler, adding more warnings for bad behaviour, with users having the option to forbid the bad behaviour entirely.

## Changelog
- Argument parsing is now a bit smarter, and supports setting arguments to values.
- Fixed OD accepting macro functors that had several variadic arguments.
- New directive unlocked! `#pragma`, which allows both us and the user to decide the elevation of various error emissions.

2022-11-16 02:11 UTC, ike709 commented on DMCompiler/Compiler/DMPreprocessor/DMPreprocessor.cs
> +                case "notice":
```suggestion
                case "notice":
                case "info":
```
pretty sure I've seen this somewhere

2022-12-01 19:13 UTC, wixoaGit requested changes

2022-12-02 03:17 UTC, ike709 commented on DMCompiler/Compiler/DM/DMParserHelper.cs
> +        protected bool Error(WarningCode code, string message) {
Maybe this should be called `TryError()` or something to distinguish it?

2022-12-04 01:52 UTC, wixoaGit approved these changes

2022-12-04 01:53 UTC, merged