Improve accuracy of world initialization sequence
OpenDreamProject/OpenDream pull request #897
Opened 2022-11-04 05:09 UTC by SpaceManiac

Splits DreamManager.Initialize into two halves:
1. PreInitialize
    1. JSON is loaded
    2. World instance is created
    3. Compiled-in turfs and areas are added to `world.contents`, and their `<init>` is called, but ALL `New` are suppressed
        * Datums created during these `<init>` never have their `New` called
2. StartWorld
    1. Global `<init>` is spawned
    2. All areas in the world have their `New()` spawned, in order
        * If global `<init>` created any areas, their New is called a second time
    4. All turfs in the world have their `New()` spawned, in reverse order
    5. All objects and mobs in compiled-in maps are `new`ed in the typical way, in order
    6. `world.New()` is spawned

Other improvements:
- Debugger calls `PreInitialize` as soon as it knows the JSON filename, but calls `StartWorld` only on ConfigurationDone
- Compiled-in areas are distinguished based on their full prototype, not just their typepath

There are still some inaccuracies:
- Compiler should assign root-level `/var/static`s before root-level `/var`s
- The various threads spawned during StartWorld could maybe combined be into one thread that calls procs as though with `waitfor = FALSE`

2022-11-11 22:49 UTC, wixoaGit commented
This appears to greatly slow down map loading.

Loading Box Station on my [stripped /tg/ fork](https://github.com/wixoaGit/tgstation) before:
`world.log: Loaded Station in 9.2s!`
After:
`world.log: Loaded Station in 326.4s!`

Haven't looked much into it yet, but I suspect this is due to the adding/removing of items on `area.contents`. Maybe this could instead be done with a special list similar to [`datum.vars`](https://github.com/OpenDreamProject/OpenDream/blob/45d41d6dbcb0b0e1e4a6c67ba710cdf7fb565106/OpenDreamRuntime/Objects/DreamList.cs#L187).

2022-11-12 04:08 UTC, SpaceManiac commented
Good call. The big contributors were UnionValue on `area.contents` and `world.contents`, which I really should have seen coming. My machine loads Box Station much slower than yours on OD master + your /tg/ branch (98.5s) but with this PR fixed it now loads about the same (104s).

2022-11-12 04:16 UTC, SpaceManiac commented
Ah, compiling OpenDreamServer in release mode gets me ~10.5s to load your Box both on OD master and this PR.

2022-11-16 02:24 UTC, wixoaGit requested changes

2022-11-16 02:24 UTC, wixoaGit commented on OpenDreamRuntime/Objects/DreamObject.cs
>              }
This can be removed entirely

2022-11-17 19:24 UTC, wixoaGit approved these changes

2022-11-17 19:24 UTC, merged