Paradise Interface Fixes
OpenDreamProject/OpenDream pull request #906
Opened 2022-11-13 17:18 UTC by amylizzle

Some fixes to our interface code to make it act more byondish. 

The first was a mistake from my DMF 0x0 fix, which treated `pos=none` as `pos=0x0`.
The second is some lovely jank where Paradise was setting `anchor2=-1,-1` which by DM ref is undefined behaviour, but seems to basically just be equivalent to `anchor2=none`. 
The third was some out-of-order components, which I thought broke BYOND's interface code in my tests, but maybe in some cases it just gets fixed silently? Now OD fixes it not-silently.

Anyway, Paradise's interface will now display unmodified and mostly correct.
![image](https://user-images.githubusercontent.com/3855802/201534904-8f394f74-a907-4b7d-9ea3-10ec15467db8.png)

2022-11-16 23:26 UTC, amylizzle commented
segfaulting, dnm

2022-12-18 00:44 UTC, wixoaGit requested changes

2022-12-18 00:44 UTC, wixoaGit commented on OpenDreamClient/Interface/Controls/ControlWindow.cs
> +                {
```suggestion
                if(ChildControls.Count > 0) {
```

2022-12-18 00:44 UTC, wixoaGit commented on OpenDreamClient/Interface/Controls/ControlWindow.cs
> +                    {
```suggestion
                    else {
```

2022-12-18 00:44 UTC, wixoaGit commented on OpenDreamClient/Interface/Controls/ControlWindow.cs
> +                        {
```suggestion
                        while(i < ChildControls.Count) {
```

2022-12-18 00:44 UTC, wixoaGit commented on OpenDreamClient/Interface/Controls/ControlWindow.cs
> +                else
```suggestion
                } else
```

2022-12-18 00:52 UTC, merged