Fixes lateral proc overrides, OD now errors on missing types promised by var definitions, and more!
OpenDreamProject/OpenDream pull request #934
Opened 2022-11-22 07:28 UTC by Altoids1

Fixes #933, and a bunch of other things that don't have issues on the repo, AFAIK.
## Summary
The main goal was to fix a range of errors that Yogs is having on master, where a proc override was appearing before its definition on the same type.

Looking into that ended up involving doing a whole mess of other bugfixes to get everything working. `/datum/do/re/mi` wasn't a valid type for some reason, some random unit tests that we were passing suddenly failed, and I had some strange issues with performance.

So this PR is more of a shotgun blast of everything necessary to squash that issue and get Yogs working. `DMObjectBuilder` grows ever more complex, I guess.

## Changelog
- Procs declared in a proc\n\tfoo() format are now properly informed of whether they are a definition or an override.
- Procs that override a proc on the exact same path now behave correctly and do not compiletime when discovered out-of-order.
- Global procs now behave better when being overridden.
- OD now properly compiletimes when a definition for an overridden proc is not discovered.
- Using the text `while`, `do`, or `for` in a type path (as in /datum/do/re/mi) is now valid and behaves as expected.
- Removed a bad unit test and added a few more!

2022-11-22 07:57 UTC, Altoids1 commented
This has https://github.com/OpenDreamProject/OpenDream/pull/935 as a dependency.

2022-11-24 22:00 UTC, ike709 commented
CI should pass now if you rerun it. The unused vars in stripped TG have been removed.

2022-11-25 19:07 UTC, Altoids1 commented
Lookin' good 😎

2023-03-01 19:01 UTC, wixoaGit requested changes

2023-03-16 02:57 UTC, wixoaGit approved these changes

2023-03-16 02:57 UTC, merged