implements try catch
OpenDreamProject/OpenDream pull request #984
Opened 2022-12-20 18:42 UTC by PaulRitter

nested throws currently dont work

2023-01-27 04:20 UTC, wixoaGit requested changes

2023-01-27 04:20 UTC, wixoaGit commented on OpenDreamRuntime/Procs/AsyncNativeProc.cs
> +            {
```suggestion
            public override ProcStatus Resume() {
```

2023-01-27 04:20 UTC, wixoaGit commented on OpenDreamRuntime/DreamThread.cs
> +                        if (TryCatchException(new DreamValue(exception.Message))) continue;
BYOND appears to turn any exception that isn't from a `throw` into an [/exception object](https://www.byond.com/docs/ref/#/exception).

2023-01-27 04:20 UTC, wixoaGit commented on OpenDreamRuntime/Procs/DMProc.cs
> +        public int CatchVarIndex = NoTryCatch;
These should be reset in either `Dispose()` or `Initialize()`

Proc states can be saved for later reuse, so it's good to not keep values between uses.

2023-01-27 04:20 UTC, wixoaGit commented on OpenDreamRuntime/Procs/DMProc.cs
> +            CatchVarIndex = catchVarIndex;
This wouldn't support nested try/catches

2023-01-27 04:20 UTC, wixoaGit commented on OpenDreamRuntime/Procs/NativeProc.cs
> +            {
```suggestion
            public override ProcStatus Resume() {
```

2023-01-27 04:40 UTC, wixoaGit commented
The `Try` and `TryNoValue` opcodes will need added to the `ProcDecoder` class, which is used by both the debugger and the decompiler.

2023-02-18 13:23 UTC, PaulRitter commented
> The `Try` and `TryNoValue` opcodes will need added to the `ProcDecoder` class, which is used by both the debugger and the decompiler.

Im unsure where i need to add these opcodes in the file, as well as how to test it. Can you ping me on discord with instructions?

2023-02-20 04:33 UTC, wixoaGit requested changes

2023-02-20 04:33 UTC, wixoaGit commented on OpenDreamRuntime/DreamThread.cs
> +        public DMCrashRuntime(string message) : base(new DreamValue(message)) { }
Using this base constructor will end up putting `'throw' thrown` at the beginning of the exception message. Probably meant to use the other one?
```suggestion
        public DMCrashRuntime(string message) : base(message) { }
```

2023-02-22 03:18 UTC, wixoaGit approved these changes

2023-02-22 03:18 UTC, merged